name: Main Test-Java14

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcversion: [ 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5 ]
        javaversion: [ 14 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.javaversion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.javaversion }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test
        uses: ./
        with:
          plugin-name: CheckPluginEnabling
          minecraft-version: ${{ matrix.mcversion }}